name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: install
        run: |
          go install ./cmd/App
          echo "$GOPATH/bin" >> $GITHUB_PATH
      - name: test
        run: go test -v -count=1 -p 1 ./...